spring:
  thymeleaf:
    mode: HTML

    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false

  profiles:
    active: dev

  messages:
    basename: i18n/messages

comment.avatar: https://picsum.photos/seed/picsum/100/100